### PR TITLE
Remove finalizer when cloud resource is found absent

### LINKED ISSUE #218: DOMachine with missing instance ID is never removed on cluster delete
When a `Cluster` is deleted while a `DOMachine` does not have have an instance ID attached (which can happen when the create failed for some reason or the control plane never became ready), the delete hangs forever [because `DOMachineReconciler` terminates reconciliation prematurely](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/ddbc69c071f9eaa7e294ddf0662825d010205774/controllers/domachine_controller.go#L274-L278). The only way to address the matter is to remove the finalizer manually.

I'm not 100% sure how to best solve the issue. One approach I can think of is to remove the DOMachine finalizer if the instance ID is missing.

### LINKED ISSUE #219: DOCluster never completes deletion when LB is missing
When a `DOCluster` never manages to create an LB, a delete on the cluster [never completes because the delete reconciler always expects an LB to be found or otherwise returns early](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/ddbc69c071f9eaa7e294ddf0662825d010205774/controllers/docluster_controller.go#L166-L170).

Same question as in #218 arises on how to address this problem, with one possible solution to move forward on a missing LB and delete the finalizer so that the `DOCluster` deletion can complete.

### PR DESCRIPTION
**Pull request by timoreimann**
**What this PR does / why we need it**:
Remove finalizer when cloud resource is found absent.

This is to ensure that reconciles can complete even when cloud resources (droplets, LBs) cannot be referenced anymore.

**Which issue(s) this PR fixes**:
Fixes #218
Fixes #219

**Release note**:
```release-note
Remove finalizer when cloud resource is found absent
```

### CODE REVIEW

File: controllers/docluster_controller.go [hunk 1]
```diff
@@ -166,14 +166,15 @@ func (r *DOClusterReconciler) reconcileDelete(ctx context.Context, clusterScope
...
+		controllerutil.RemoveFinalizer(docluster, infrav1.ClusterFinalizer)
 		return reconcile.Result{}, nil
 	}
 
 	if err := networkingsvc.DeleteLoadBalancer(loadbalancer.ID); err != nil {
 		return reconcile.Result{}, errors.Wrapf(err, "error deleting load balancer for DOCluster %s/%s", docluster.Namespace, docluster.Name)
 	}
 
-	r.Recorder.Eventf(docluster, corev1.EventTypeNormal, "LoadBalancerDeleted", "Deleted a instance - %s", loadbalancer.Name)
+	r.Recorder.Eventf(docluster, corev1.EventTypeNormal, "LoadBalancerDeleted", "Deleted an instance - %s", loadbalancer.Name)
```
Comment (xmudrii) [inline controllers/docluster_controller.go:177]: Should this be LoadBalancer instead?
```suggestion
	r.Recorder.Eventf(docluster, corev1.EventTypeNormal, "LoadBalancerDeleted", "Deleted an LoadBalancer - %s", loadbalancer.Name)
```

**Review by xmudrii — COMMENTED** [review]
Tiny nit otherwise looks fine to me.

File: controllers/docluster_controller.go (hunk 1 above)
Comment (timoreimann) [reply controllers/docluster_controller.go:177]: Ah yeah totally, a prior copy-pasta.

**Comment by timoreimann** [comment]
@xmudrii implemented your suggestion, thanks.

**Review by prksu — APPROVED** [review]
/lgtm
/approve
